[package]
name = "iot-access"
version = "0.1.0"
edition = "2024"

[dependencies]
ecat = { path = "../ecat" }
ecat-transport-http.workspace = true
ecat-data-sqlx = { path = "../ecat-data-sqlx" }
ecat-data-redis = { path = "../ecat-data-redis" }
ecat-mq-kafka = { path = "../ecat-mq-kafka" }
ecat-mq-mqtt = { path = "../ecat-mq-mqtt" }
ecat-middleware = { path = "../ecat-middleware" }
ecat-health = { path = "../ecat-health" }
ecat-access = { path = "../ecat-access" }
axum.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
async-trait.workspace = true
base64 = "0.22"
ecat-data = { path = "../ecat-data" }
ecat-mq = { path = "../ecat-mq" }
ecat-security = { path = "../ecat-security" }
futures-util = "0.3"
hex = "0.4"
hmac = "0.12"
serde_json.workspace = true
sha2.workspace = true
tower-util = "0.3"
tower.workspace = true
