[package]
name = "iot-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
ecat = { path = "../ecat" }
ecat-auth.workspace = true
ecat-transport-http.workspace = true
ecat-health = { path = "../ecat-health" }
ecat-security = { path = "../ecat-security" }
ecat-gateway = { path = "../ecat-gateway" }
axum.workspace = true
reqwest = { version = "0.12", features = ["json"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
jsonwebtoken = "9"
tower-util = "0.3"
tower.workspace = true
serde.workspace = true
