[package]
name = "iot-rule"
version = "0.1.0"
edition = "2024"

[dependencies]
ecat = { path = "../ecat" }
ecat-transport-http.workspace = true
ecat-data-sqlx = { path = "../ecat-data-sqlx" }
ecat-middleware = { path = "../ecat-middleware" }
ecat-health = { path = "../ecat-health" }
ecat-mq-kafka = { path = "../ecat-mq-kafka" }
ecat-rule = { path = "../ecat-rule" }
axum = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
ecat-auth = { path = "../ecat-auth" }
ecat-data = { path = "../ecat-data" }
serde_json.workspace = true
tower-util = "0.3"
tower.workspace = true
jsonwebtoken = "9"
