[package]
name = "ecat-gateway"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "iot-gateway"
path = "src/main.rs"

[dependencies]
ecat = { path = "../ecat" }
ecat-auth = { path = "../ecat-auth" }
ecat-transport.workspace = true
ecat-transport-http.workspace = true
ecat-health = { path = "../ecat-health" }
ecat-security = { path = "../ecat-security" }
ecat-middleware = { path = "../ecat-middleware", features = ["redis"] }
ecat-data = { path = "../ecat-data" }
ecat-search = { path = "../ecat-search" }
ecat-data-sqlx = { path = "../ecat-data-sqlx" }
ecat-openapi = { path = "../ecat-openapi" }
ecat-registry = { path = "../ecat-registry" }
ecat-registry-consul = { path = "../ecat-registry-consul" }
async-trait.workspace = true
axum.workspace = true
http.workspace = true
tower.workspace = true
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[dev-dependencies]
jsonwebtoken = "9"
serde.workspace = true
tower-util = "0.3"
