[package]
name = "iot-device"
version = "0.1.0"
edition = "2024"

[dependencies]
ecat = { path = "../ecat" }
ecat-transport-http.workspace = true
ecat-data-sqlx = { path = "../ecat-data-sqlx" }
ecat-health = { path = "../ecat-health" }
ecat-device = { path = "../ecat-device" }
axum.workspace = true
tokio = { workspace = true, features = ["full"] }
